server:
  port: ${BACKEND_PORT:8080}

spring:
  application:
    name: hotelreservation

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    format-sql: true
    properties:
      hibernate.default_batch_fetch_size: 50
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT_HOST:5432}/${DB_NAME:hotel-reservation}?reWriteBatchedInserts=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include:
          - health
    health:
      show-details: always
